<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
     public function run(): void
     {
         $menus = [
             [
                 'nama_menu' => 'Kue Lapis',
                 'kategori' => 'Dessert',
                 'deskripsi' => 'kue lapis tradisional manis lembut',
                 'harga' => 12000,
                 'gambar' => '1.png',
                 'rating' => 4.7,
                 'stok' => 80,
                 'kalori' => 180,
                 'protein' => 3,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Kelepon',
                 'kategori' => 'Dessert',
                 'deskripsi' => 'kelepon isi gula merah kelapa',
                 'harga' => 10000,
                 'gambar' => '2.png',
                 'rating' => 4.6,
                 'stok' => 90,
                 'kalori' => 150,
                 'protein' => 2,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Onde Onde',
                 'kategori' => 'Dessert',
                 'deskripsi' => 'onde onde wijen isi kacang hijau',
                 'harga' => 12000,
                 'gambar' => '3.png',
                 'rating' => 4.7,
                 'stok' => 50,
                 'kalori' => 220,
                 'protein' => 4,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Kue Putu',
                 'kategori' => 'Dessert',
                 'deskripsi' => 'kue putu pandan isi gula merah',
                 'harga' => 10000,
                 'gambar' => '4.png',
                 'rating' => 4.8,
                 'stok' => 60,
                 'kalori' => 160,
                 'protein' => 2,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Bika Ambon',
                 'kategori' => 'Dessert',
                 'deskripsi' => 'bika ambon khas medan lembut',
                 'harga' => 15000,
                 'gambar' => '5.png',
                 'rating' => 4.9,
                 'stok' => 45,
                 'kalori' => 240,
                 'protein' => 5,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Serabi',
                 'kategori' => 'Dessert',
                 'deskripsi' => 'serabi tradisional gurih manis',
                 'harga' => 10000,
                 'gambar' => '6.png',
                 'rating' => 4.7,
                 'stok' => 70,
                 'kalori' => 170,
                 'protein' => 3,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Donat',
                 'kategori' => 'Dessert',
                 'deskripsi' => 'donat topping coklat warna warni',
                 'harga' => 12000,
                 'gambar' => '7.png',
                 'rating' => 4.5,
                 'stok' => 100,
                 'kalori' => 290,
                 'protein' => 4,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Risol',
                 'kategori' => 'Snack',
                 'deskripsi' => 'risol goreng isi sayur dan mayo',
                 'harga' => 10000,
                 'gambar' => '8.png',
                 'rating' => 4.8,
                 'stok' => 95,
                 'kalori' => 190,
                 'protein' => 5,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Lemper',
                 'kategori' => 'Snack',
                 'deskripsi' => 'lemper ayam dibungkus daun pisang',
                 'harga' => 10000,
                 'gambar' => '9.png',
                 'rating' => 4.8,
                 'stok' => 120,
                 'kalori' => 200,
                 'protein' => 6,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Bronis',
                 'kategori' => 'Dessert',
                 'deskripsi' => 'brownies coklat lembut manis',
                 'harga' => 15000,
                 'gambar' => '10.png',
                 'rating' => 4.8,
                 'stok' => 40,
                 'kalori' => 320,
                 'protein' => 5,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Paket Specials',
                 'kategori' => 'Corporate',
                 'deskripsi' => 'paket catering menu spesial lengkap dengan olahan terbaik',
                 'harga' => 30000,
                 'gambar' => '11.png',
                 'rating' => 4.9,
                 'stok' => 50,
                 'kalori' => 650,
                 'protein' => 28,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Paket Hemat',
                 'kategori' => 'Personal',
                 'deskripsi' => 'paket catering hemat ekonomis dan lezat',
                 'harga' => 25000,
                 'gambar' => '12.png',
                 'rating' => 4.7,
                 'stok' => 100,
                 'kalori' => 550,
                 'protein' => 20,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Paket Sultan',
                 'kategori' => 'Event',
                 'deskripsi' => 'paket catering premium lengkap dengan berbagai menu pilihan',
                 'harga' => 50000,
                 'gambar' => '13.png',
                 'rating' => 4.9,
                 'stok' => 30,
                 'kalori' => 850,
                 'protein' => 45,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Birthday Cake',
                 'kategori' => 'Event',
                 'deskripsi' => 'custom birthday cake berbagai rasa yang premium',
                 'harga' => 75000,
                 'gambar' => '14.png',
                 'rating' => 4.8,
                 'stok' => 15,
                 'kalori' => 400,
                 'protein' => 8,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Snackbox Hemat',
                 'kategori' => 'Personal',
                 'deskripsi' => 'paket snackbox hemat isi lengkap kue basah',
                 'harga' => 20000,
                 'gambar' => '15.png',
                 'rating' => 4.6,
                 'stok' => 150,
                 'kalori' => 380,
                 'protein' => 10,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Snackbox Hajat',
                 'kategori' => 'Event',
                 'deskripsi' => 'snackbox acara hajatan lengkap dan lezat',
                 'harga' => 25000,
                 'gambar' => '16.png',
                 'rating' => 4.7,
                 'stok' => 200,
                 'kalori' => 450,
                 'protein' => 12,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Snackbox Sultan',
                 'kategori' => 'Corporate',
                 'deskripsi' => 'snackbox premium isi lengkap dan kue premium',
                 'harga' => 35000,
                 'gambar' => '17.png',
                 'rating' => 4.9,
                 'stok' => 100,
                 'kalori' => 550,
                 'protein' => 15,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Nasi Kuning',
                 'kategori' => 'Personal',
                 'deskripsi' => 'nasi kuning lauk lengkap dengan sambal dan telur',
                 'harga' => 25000,
                 'gambar' => '18.png',
                 'rating' => 4.8,
                 'stok' => 80,
                 'kalori' => 580,
                 'protein' => 22,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Nasi Ayam Geprek',
                 'kategori' => 'Personal',
                 'deskripsi' => 'nasi ayam geprek sambal pedas membakar lidah',
                 'harga' => 22000,
                 'gambar' => '19.png',
                 'rating' => 4.7,
                 'stok' => 120,
                 'kalori' => 610,
                 'protein' => 26,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Nasi Ayam Bakar',
                 'kategori' => 'Corporate',
                 'deskripsi' => 'nasi ayam bakar bumbu kecap madu khas',
                 'harga' => 25000,
                 'gambar' => '20.png',
                 'rating' => 4.8,
                 'stok' => 100,
                 'kalori' => 590,
                 'protein' => 25,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Nasi Katsu',
                 'kategori' => 'Personal',
                 'deskripsi' => 'nasi ayam katsu saus spesial jepang',
                 'harga' => 25000,
                 'gambar' => '21.png',
                 'rating' => 4.8,
                 'stok' => 90,
                 'kalori' => 640,
                 'protein' => 24,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Nasi Ayam Uduk',
                 'kategori' => 'Personal',
                 'deskripsi' => 'nasi uduk ayam lengkap dengan serundeng gurih',
                 'harga' => 23000,
                 'gambar' => '22.png',
                 'rating' => 4.7,
                 'stok' => 85,
                 'kalori' => 600,
                 'protein' => 23,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Nasi Bakar',
                 'kategori' => 'Personal',
                 'deskripsi' => 'nasi bakar isi ayam dan sambal dibungkus daun pisang',
                 'harga' => 22000,
                 'gambar' => '23.png',
                 'rating' => 4.8,
                 'stok' => 60,
                 'kalori' => 520,
                 'protein' => 21,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Nasi Goreng',
                 'kategori' => 'Corporate',
                 'deskripsi' => 'nasi goreng seafood spesial dengan udang dan cumi',
                 'harga' => 20000,
                 'gambar' => '24.png',
                 'rating' => 4.8,
                 'stok' => 75,
                 'kalori' => 670,
                 'protein' => 27,
                 'is_available' => true,
             ],
             [
                 'nama_menu' => 'Seblak',
                 'kategori' => 'Personal',
                 'deskripsi' => 'seblak pedas topping lengkap sosis, bakso, ceker',
                 'harga' => 18000,
                 'gambar' => '25.png',
                 'rating' => 4.6,
                 'stok' => 80,
                 'kalori' => 450,
                 'protein' => 14,
                 'is_available' => true,
             ],
         ];

         foreach ($menus as $menu) {
             Product::create($menu);
         }
     }
}
